### ISSUE TITLE
1.4.7 does not work on home assistant

### ISSUE THREAD

**Issue by Flirina** [markusmauch/homeassistant-addons#2]
hi Markus,
I updates yesterday the solix2mqtt version on home assistant.
after that the hacs integration is unable to start:

the log shows only:

env: can't execute 'bash': No such file or directory

pls check 
many thx
florian

**Comment by Flirina** [comment]
i restored in hacs to 1.3.4 and the add-on started to work again.

**Comment by olivr2s** [comment]
I wanted to update, but it didn't happen due to an error. Here is the log with the error.

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:13:03 (2 occurrences)
Last logged: 12:14:13

[281471963037120] Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
[281471683885760] Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 55, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:13:03 (2 occurrences)
Last logged: 12:14:13

[281471963037120] Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
[281471683885760] Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 55, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Solix 2 MQTT: The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1
`

**Comment by TabTwo** [comment]
my error with 1.4.7 is "The command '/bin/sh -c pip install cryptography aiohttp paho-mqtt' returned a non-zero code: 1" 
Neither update or new install works for this version

**Comment by markusmauch** [comment]
Sorry guys, [bashio](https://github.com/hassio-addons/bashio?tab=readme-ov-file) gave my a hard time. I replaced it by fetching the config values manually. It should work better now...

With Version 1.4.x you should be able to see the parameters of all sites. Here the siteId is 'Balkonsolar' and the mqtt topic is 'anker/solix':

![image](https://github.com/markusmauch/homeassistant-addons/assets/7030408/3303225b-bd82-482a-b5db-370695f75d5b)
(screenshot taken from MQTT explorer)

**Comment by TabTwo** [comment]
Update on 1.6.5 worked, thank you!
